version: "3.9"

services:
  #databases
  menu-backend-db:
    environment:
      - POSTGRES_PASSWORD=123
    image: postgres
    container_name: MENUDB
    ports:
      - "5432:5432"
    volumes:
      - menuDbVol:/app/services/menu
    restart: always

  order-backend-db:
    environment:
      - POSTGRES_PASSWORD=123
    image: postgres
    container_name: ORDERDB
    ports:
      - "5431:5432"
    volumes:
      - orderDbVol:/app/services/order
    restart: always

  admin-backend-db:
    environment:
      - POSTGRES_PASSWORD=123
    image: mongo
    container_name: ADMINDB
    ports:
      - "27017:27017"
    volumes:
      - adminDbVol:/app/services/admin
    restart: always

  #backend services
  
  discovery-server: ####

  config-server: ###

  admin-backend: ###

  menu-command-service:
    environment:
      - WRITE_ENABLED=true
      - APP_PORT=1001
    image: menu-service/command
    container_name: menu-command-service
    build:
      context: ./kafe-backend/menu
      dockerfile: Dockerfile-command
    depends_on:
      - menu-backend-db
    ports:
      - "1001:1001"
    restart: always

  menu-query-service:
    environment:
      - WRITE_ENABLED=false
      - APP_PORT=1002 
    image: menu-service/query
    container_name: menu-query-service
    build:
      context: ./kafe-backend/menu
      dockerfile: Dockerfile-query
    depends_on:
      - menu-backend-db
    ports:
      - "1002:1002"
    restart: always

  order-command-service:
    environment:
      - WRITE_ENABLED=true
      - APP_PORT=1004
    image: menu-service/command
    container_name: order-command-service
    build:
      context: ./kafe-backend/order
      dockerfile: Dockerfile-command
    depends_on:
      - menu-backend-db
    ports:
      - "1004:1004"
    restart: always

  order-query-service:
    environment:
      - WRITE_ENABLED=false
      - APP_PORT=1003
    image: menu-service/query
    container_name: order-query-service
    build:
      context: ./kafe-backend/order
      dockerfile: Dockerfile-query
    depends_on:
      - order-backend-db
    ports:
      - "1003:1003"
    restart: always

#networks:
#  kolayKafeNetwork:

volumes:
  menuDbVol:
  adminDbVol:
  orderDbVol: