services:
  keycloak_serv:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_db
      KC_DB_URL_DATABASE: ADMIN_USER
      KC_DB_PASSWORD: 123
      KC_DB_USERNAME: kafe_admin
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8091:8080"
    depends_on: 
      - keycloak_db

  keycloak_db:
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    volumes: 
      - pgdata_keycloak_vol:/var/lib/postgres/sql/data
    environment:
      POSTGRES_DB: ADMIN_USER
      POSTGRES_USER: kafe_admin
      POSTGRES_PASSWORD: 123
    healthcheck:
      test: "exit 0"
    ports:
      - "5450:5432"

volumes:
  pgdata_keycloak_vol:
