FROM openjdk:17-alpine

ENV WRITE_ENABLED=true
ENV APP_PORT=1001

WORKDIR app-menu
COPY "./build/libs/menu-0.0.1-SNAPSHOT.jar" ./app-command.jar
EXPOSE 1001
ENTRYPOINT ["java","-jar","./app-command.jar"]