spring:
  datasource:
    url: jdbc:postgresql://localhost:5429/users_db
    username: postgres
    password: 123
  initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
