spring:
  application:
    name: kolay-kafe-conf?g-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RazboN/sb-cloud-demo-configuration-server
          username: RazboN
<<<<<<< HEAD
          password:
=======
          password: 
>>>>>>> refs/remotes/origin/main
          clone-on-start: true

server:
  port: 1080
